Docker query parameters
ConnorMacKenzieLayer/docker-dashboard pull request #2
Opened 2021-10-12 06:00 UTC by Peter8234

address issue https://github.com/ColinChartier/webapp.io/issues/617

- Docker dashboard can now connect to multiple jobs by accessing their query parameters
- Added a back button to container page

2021-10-19 22:26 UTC, ConnorMacKenzieLayer requested changes
A few things to change:
- remove debugging code
- make job uuid first parameter in path
- the name uuid is unclear, can it be called job uuid

2021-10-20 05:42 UTC, Peter8234 commented on docker-dashboard-front-end/src/dashboard/Container.js
> +            const result = await res.json()
the results were a part of the debugging process I wanted to test if the endpoint worked nothing is being done there I forgot to remove the debugging elements of the code

2021-10-20 20:33 UTC, ConnorMacKenzieLayer requested changes

2021-10-20 20:33 UTC, ConnorMacKenzieLayer commented on docker-dashboard-front-end/src/App.js
> +            <Route exact path="/:jobuuid">
can you camel case `jobUuid` for readability

2021-10-20 20:33 UTC, ConnorMacKenzieLayer commented on docker-dashboard-front-end/src/dashboard/Container.js
> +            <IconButton onClick={() => history.goBack()}>
Can this be an href rather than history so we explicitly know the page it is returning to

2021-10-21 18:53 UTC, merged